= TeX-Bot-Py-V2
Matthew Norton <matt@carrotmanmatt.com>
v1.0, 25/03/2024

ifndef::env-idea[]
include::.asciidoctorconfig[]
endif::[]

image:https://img.shields.io/badge/dynamic/toml?url=https%3A%2F%2Fraw.githubusercontent.com%2FCSSUoB%2FTeX-Bot-Py-V2%2Fmain%2Fpyproject.toml&query=%24.tool.poetry.version&label=TeX-Bot[TeX-Bot Version,link={url-project-repo}]
image:https://img.shields.io/badge/Python-3.12-blue?&logo=Python&logoColor=white[Python Version,link={url-python-312}]
image:https://img.shields.io/badge/dynamic/toml?url=https%3A%2F%2Fraw.githubusercontent.com%2FCSSUoB%2FTeX-Bot-Py-V2%2Fmain%2Fpyproject.toml&query=%24.package%5B%3F%28%40.name%3D%3D%27py-cord%27%29%5D.version&logo=Discord&label=Pycord&logoColor=white[Pycord Version,link={url-pycord}]
image:{url-project-repo}/actions/workflows/tests.yaml/badge.svg[Tests Status,link={url-project-repo}/actions/workflows/tests.yaml]
image:https://img.shields.io/badge/mypy-checked-%232EBB4E&label=mypy[Mypy Status,link={url-mypy}]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/ruff/main/assets/badge/v2.json[Ruff,link={url-ruff}]
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit[pre-commit Status,link={url-pre-commit}]
image:https://img.shields.io/badge/validated-brightgreen?logo=asciidoctor&logoColor=white&label=AsciiDoc[AsciiDoc Status,link={url-asciidoc}]

{url-tex-bot-js}[TeX-Bot], but back in {labelled-url-python}!
This is a {url-discord-wiki-bot}[Discord bot] used for managing a community group's {labelled-url-discord} {url-discord-wiki-guild}[guild].

Featured in the {url-uob-css-discord}[CSS Discord guild].

[#terminology]
== Terminology

[#guild-vs-server]
=== {url-discord-wiki-guild}["Guild"] Vs {url-discord-wiki-guild-not-server}["Server"]

Confusingly, {labelled-url-discord} uses the term {url-discord-wiki-guild}["guild"] to refer to a {url-discord-wiki-guild-not-server}[Discord "server"], when communicating  with developers.
Therefore, the same terminology {url-discord-wiki-guild}["guild"] will be used across all documentation in this project.
(See {url-discord-wiki-guild}[the Discord developer docs] & {url-pycord-wiki-guild}[Pycord's docs] for more information.)

The term "main guild" is used throughout the code in this repository to refer specifically to your community group's main {url-discord-wiki-guild}[Discord guild].

[#user-vs-member-vs-guest]
=== "User" Vs "Member" Vs "Guest"

[#user-vs-member-vs-guest-discord-objects]
==== {url-discord-wiki}[Discord Objects]

In the context of {labelled-url-discord} itself, a {url-discord-wiki-user}["user"] object represents a {labelled-url-discord} account not connected to any specific {url-discord-wiki-guild}[guild].
Therefore, it can be {url-wiki-dm}[messaged via DM] or be retrieved via its {url-discord-wiki-snowflake}[snowflake ID], but little else can be done with it.
(See {url-discord-wiki-user}[the Discord developer docs] & https://docs.pycord.dev/en/stable/api/models.html#users[Pycord's docs] for more information.)

In contrast, a {url-discord-wiki-member}[Discord "member"] object is a {url-discord-wiki-user}["user"] attached to a specific {url-discord-wiki-guild}[guild].
Therefore, it can have {url-discord-wiki-role}[roles], be {url-discord-wiki-ban}[banned] & have many other actions applied to it.
(See {url-discord-wiki-member}[the Discord developer docs] & {url-pycord-wiki-member}[Pycord's docs]) for more information.)

[#user-vs-member-vs-guest-community-group-membership]
==== Community Group Membership

In the context of your community group's membership structure, a "member" is a person that has purchased a membership to join your community group.
This is in contrast to a "guest", which is a person that has not purchased a membership.
Guests often can only attend events that are open to anyone (i.e. **not** members only), and have limited communication/perks within your {url-discord-wiki-guild}[Discord guild].
Some commands may require you to create {url-discord-wiki-role}[roles] within your {url-discord-wiki-guild}[Discord guild], to differentiate between these different types of users.

[#user-vs-member-vs-guest-other-uses]
==== Other Uses

In some other contexts, the term "user" may be used to refer to any person/organisation making use of this project.
(E.g. the description within xref:error-codes[the "Error Codes" section].)

[#error-codes]
== Error Codes

Users of TeX-Bot may encounter an error code when executing a slash-command fails.
If a user encounters any of these errors, please communicate the error to the committee member that has been assigned to upkeep & deployment of your instance of TeX-Bot.
The meaning of each error code is given here:

`+E1011+`:: The value for the {url-wiki-environment-variables}[environment variable] `+DISCORD_GUILD_ID+` is an {url-discord-wiki-snowflake}[ID] that references a {url-discord-wiki-guild}[Discord guild] that does not exist

`+E1021+`:: Your {url-discord-wiki-guild}[Discord guild] does not contain a {url-discord-wiki-role}[role] with the name "@*Committee*".
(This {url-discord-wiki-role}[role] is required for the `+/writeroles+`, `+/editmessage+`, `+/induct+`, `+/strike+`, `+/archive+`, `+/delete-all+` & `+/ensure-members-inducted+` {url-discord-wiki-command}[commands])

`+E1022+`:: Your {url-discord-wiki-guild}[Discord guild] does not contain a {url-discord-wiki-role}[role] with the name "@*Guest*".
(This {url-discord-wiki-role}[role] is required for the `+/induct+`, `+/stats+`, `+/archive+` & `+/ensure-members-inducted+` {url-discord-wiki-command}[commands] and the `+kick_no_introduction_discord_members+` & `+introduction_reminder+` {url-pycord-wiki-task}[tasks])

`+E1023+`:: Your {url-discord-wiki-guild}[Discord guild] does not contain a {url-discord-wiki-role}[role] with the name "@*Member*".
(This {url-discord-wiki-role}[role] is required for the `+/makemember+` & `+/ensure-members-inducted+` {url-discord-wiki-command}[commands])

`+E1024+`:: Your {url-discord-wiki-guild}[Discord guild] does not contain a {url-discord-wiki-role}[role] with the name "@*Archivist*".
(This {url-discord-wiki-role}[role] is required for the `+/archive+` {url-discord-wiki-command}[command])

`+E1031+`:: Your {url-discord-wiki-guild}[Discord guild] does not contain a {url-discord-wiki-channel-text}[text channel] with the name "#*roles*".
(This {url-discord-wiki-channel-text}[text channel] is required for the `+/writeroles+` {url-discord-wiki-command}[command])

`+E1032+`:: Your {url-discord-wiki-guild}[Discord guild] does not contain a {url-discord-wiki-channel-text}[text channel] with the name "#*general*".
(This {url-discord-wiki-channel-text}[text channel] is required for the `+/induct+` {url-discord-wiki-command}[command])

`+E1041+`:: The community group member IDs could not be retrieved from the `+MEMBERS_LIST_URL+`.
(It is likely that your `+MEMBERS_LIST_URL_SESSION_COOKIE+` is invalid.
If your community group is a {labelled-url-guild-of-students} {url-wiki-student-society}[society], the community group member IDs will be a list of {url-guild-of-students-wiki-uob-id}[UoB IDs])

`+E1042+`:: The reference to the `+@everyone+` role could not be correctly retrieved.
Try running the command that caused this error again.
If the error persists, please file an issue on {url-project-bug-tracker}[this project's bug tracker], including the details of what command was run to create this error

`+E1043+`:: A button callback interaction did not contain the related user.
Try pressing the button that caused this error again.
If the error persists, please file an issue on {url-project-bug-tracker}[this project's bug tracker], including the details of what command was run to create this error

`+E1044+`:: An interaction was denied because the Discord permissions for TeX-Bot were not set correctly

[#log-entry-error-levels]
== Log-Entry Error Levels

When an error occurs, a log entry will be created.
One of these possible error levels will be associated with that log entry.
Below are the explanations of what effects/causes each log-level represents:

`+WARNING+`:: An error occurred that did *_not_ result in any failure to complete the current request/interaction*.
However, some minor inconsistencies/data loss may have occurred.
This may require some changes to the deployment configuration or {url-project-bug-tracker}[an issue about a bug to be raised]

`+ERROR+`:: The current *request/interaction could _not_ be completed* due to a major error.
The problem that caused the error should be addressed *immediately*, or otherwise TeX-Bot should be manually shut down to prevent further errors

`+CRITICAL+`:: An **unrecoverable error occurred**.
This level of error will cause TeX-Bot to shut down, as the problem can only be solved by fixing one or more of the {url-wiki-environment-variables}[configuration environment variables]

[#repeated-tasks-conditions]
== Repeated Tasks Conditions

The {url-wiki-environment-variables}[configuration variables] `+SEND_INTRODUCTION_REMINDERS+`, `+SEND_GET_ROLES_REMINDERS+` & `+KICK_NO_INTRODUCTION_DISCORD_MEMBERS+` determine whether their related {url-pycord-wiki-task}[tasks] should run.
However, because these are rather annoying/drastic actions to be executed automatically, there are additional conditions that must be met on a per-link:{url-discord-wiki-member}[member] basis for the action to trigger.
The conditions for each {url-pycord-wiki-task}[task] are listed below, along with the additional {url-wiki-environment-variables}[environment variables] that can be used to configure the conditions to suit your needs.

[cols="l,a,a,d"]
|===
|Task Name |Enable/Disable |Scheduled Interval |Per-Member Conditions

|introduction_reminder
|`+SEND_INTRODUCTION_REMINDERS+`:

`+Once+`:: Only send the introduction reminder once (even if they later delete the message)
`+Interval+`:: Send an introduction reminder at a set interval
`+False+`:: Do not send introduction reminders
|* The {url-discord-wiki-member}[Discord member] has not been inducted (does not have the "@*Guest*" {url-discord-wiki-role}[role])
* The time since the {url-discord-wiki-member}[Discord member] joined is greater than the maximum out of 1 day or one third of `+KICK_NO_INTRODUCTION_DISCORD_MEMBERS_DELAY+`
* The {url-discord-wiki-member}[Discord member] has not opted out of introduction reminders
* The {url-discord-wiki-member}[Discord member] has not yet been sent an introduction reminder.
Only applied when `+SEND_INTRODUCTION_REMINDERS+` is set to the value `+Once+`
|The interval of time between this task running is determined by `+SEND_INTRODUCTION_REMINDERS_INTERVAL+`.
(When `+SEND_INTRODUCTION_REMINDERS+` is set to the value `+Once+`, all {url-discord-wiki-member}[Discord members] will still be checked at this interval, just not sent a message if they have already been sent an introduction reminder)

|kick_no_introduction_discord_members
|`+KICK_NO_INTRODUCTION_DISCORD_MEMBERS+`:

`+True+`:: {url-discord-wiki-member}[Discord members] that meet the per-link:{url-discord-wiki-member}[member] conditions will be kicked from your {url-discord-wiki-guild}[guild]
`+False+`:: No {url-discord-wiki-member}[Discord members] will ever be kicked
|* The {url-discord-wiki-member}[Discord member] has not been inducted (does not have the "@*Guest*" {url-discord-wiki-role}[role])
* The time since the {url-discord-wiki-member}[Discord member] joined is greater than `+KICK_NO_INTRODUCTION_DISCORD_MEMBERS_DELAY+`
|This task is run every 24 hours

|get_roles_reminder
|`+SEND_GET_ROLES_REMINDERS+`:

`+True+`:: A single reminder for the {url-discord-wiki-member}[Discord member] to get {url-discord-wiki-role}[roles] will be sent to them only once (even if they later delete the message)
`+False+`:: Do not send any reminders for {url-discord-wiki-member}[Discord members] to get {url-discord-wiki-role}[roles]
|* The {url-discord-wiki-member}[Discord member] has been inducted (has the "@*Guest*" {url-discord-wiki-role}[role])
* The {url-discord-wiki-member}[Discord member] does not have any of the opt-in {url-discord-wiki-role}[roles].
(E.g. "@*First Year*" or "@*Anime*".)
(Having the green "@*Member*" {url-discord-wiki-role}[role] or even the "@*Committee*" {url-discord-wiki-role}[role] makes no difference)
* The time since the {url-discord-wiki-member}[Discord member] was inducted (gained the "@*Guest*" {url-discord-wiki-role}[role]) is greater than 1 day
* The {url-discord-wiki-member}[Discord member] has not yet been sent a reminder to get {url-discord-wiki-role}[roles]
|The interval of time between this task running is determined by `+SEND_GET_ROLES_REMINDERS_INTERVAL+`
|===

[#deploying-in-production]
== Deploying in Production

The only supported way to deploy TeX-Bot in production is by using our pre-built {url-docker-wiki-container}[docker container].
It is link:.github/workflows/update-container-image.yaml[built automatically] when new changes are made to {url-project-main-branch}[the `+main+` branch], and can be pulled from the {url-github-wiki-container-registry}[GitHub Container Registry] with this identifier: {url-project-package}[`+ghcr.io/CSSUoB/tex-bot-py-v2:latest+`].
(An introduction on how to use a {url-docker-wiki-compose}[docker-compose deployment] can be found {url-docker-guide-compose}[here].)

Before running the {url-docker-wiki-container}[container], some {url-wiki-environment-variables}[environment variables] will need to be set.
These can be defined in your {url-docker-wiki-compose-file-format}[`+compose.yaml+`] file.
The required {url-wiki-environment-variables}[environment variables] are explained within xref:setting-environment-variables[the "Setting Environment Variables" section].

[#local-deployment]
== Local Deployment

[#installing-dependencies]
=== Installing Dependencies

. Ensure that you have {labelled-url-poetry} installed
. Navigate to this project's repository root folder
. To install the required dependencies, execute the following command:
+
--
[source,console]
$ poetry install --no-root --sync # <1> <2>

<1> The {url-poetry-wiki-cli-install-options}[`+--no-root+` flag] installs the dependencies without installing the {url-wiki-python-project}[root project] as a {url-wiki-python-distribution-package}[package].
{labelled-url-poetry} attempts to install the {url-wiki-python-project}[project] as a {url-wiki-python-distribution-package}[package] by default because {labelled-url-poetry} is often used to develop {url-wiki-python-distribution-package}[library packages], which need to be installed themselves.

<2> The {url-poetry-wiki-cli-install-options}[`+--sync+` flag] uninstalls any additional {url-wiki-python-distribution-package}[packages] that have already been installed in the {url-wiki-python-virtual-environment}[local environment], but are not required in the link:pyproject.toml[`+pyproject.toml+`]
--

[#activating-the-poetry-environment]
=== Activating the {labelled-url-poetry} {url-wiki-python-virtual-environment}[Environment]

To use the installed dependencies, the {url-wiki-python-virtual-environment}[environment] they were installed within must be activated.
The easiest way to do this (as described by {url-poetry-wiki-activating-the-virtual-environment}[Poetry's guide]) is with the below command:

[source,console]
$ poetry shell

If you do not want to activate the {url-wiki-python-virtual-environment}[virtual environment], every {url-wiki-terminal-command}[command] can be run prepended with {url-poetry-wiki-cli-run}[`+poetry run+`], to run the given {url-wiki-terminal-command}[command] within the {url-poetry-wiki-activating-the-virtual-environment}[Poetry context].
(Every {url-wiki-terminal-command}[command] within the documentation within this project will include the {url-poetry-wiki-cli-run}[`+poetry run+`] prefix for convenience.
**It can be excluded if you have already {url-poetry-wiki-activating-the-virtual-environment}[activated the virtual environment].**)

[#creating-your-bot]
=== Creating Your {url-discord-wiki-bot}[Bot]

A full guide to create your bot's account can be found {url-pycord-wiki-bot-creation}[here; on Pycord's wiki].

You'll need to create a {url-discord-wiki-bot}[Discord bot] of your own in the {url-discord-developer-portal}[Discord Developer Portal].
It's also handy if you have an empty {url-discord-wiki-guild}[guild] for you to test in.

You can retrieve the correct {url-pycord-wiki-bot-invitation}[invite URL] to use by navigating to the root folder, then running the following command:

[source,console]
$ poetry run python -m utils generate_invite_url {discord_bot_application_id} {discord_guild_id} # <1> <2>

<1> `+{discord_bot_application_id}+` must be replaced by the {url-discord-developer-portal}[application ID] of your {url-discord-wiki-bot}[bot]
<2> `+{discord_guild_id}+` must be replaced by the {url-discord-wiki-snowflake}[snowflake ID] of your community group's {url-discord-wiki-guild}[guild]

[#setting-environment-variables]
=== Setting {url-wiki-environment-variables}[Environment Variables]

You'll also need to set a number of {url-wiki-environment-variables}[environment variables] before running TeX-Bot:

`+DISCORD_BOT_TOKEN+`:: The {url-discord-wiki-bot-token}[secret token] for the {url-discord-wiki-bot}[instance of TeX-Bot] you created.
(The {url-discord-wiki-bot-token}[token] is available on {url-discord-developer-portal}[your bot page in the Developer Portal].)

`+DISCORD_GUILD_ID+`:: The {url-discord-wiki-snowflake}[ID] of your {url-discord-wiki-guild}[Discord guild].

`+DISCORD_LOG_CHANNEL_WEBHOOK_URL+`:: The {url-discord-wiki-webhook}[webhook URL] of the {url-discord-wiki-channel-text}[Discord text channel] where error log messages should be sent.
(This setting is optional.
Error logs will *always* be sent to the {url-wiki-terminal}[console], this setting allows them to also be sent to a {url-discord-wiki-channel-text}[Discord log channel].)

`+MEMBERS_LIST_URL+`:: The {labelled-url-wiki-url} to retrieve the list of IDs of people that have purchased a membership to your community group.
(The {labelled-url-uob-css}' members-list is currently found on {url-guild-of-students-home}[the Guild of Students website].
If your members-list is also found on {url-guild-of-students-home}[the Guild of Students website], ensure the {labelled-url-wiki-url} includes the "sort by groups" option, so that all members are visible without {url-wiki-pagination}[pagination].)

`+MEMBERS_LIST_URL_SESSION_COOKIE+`:: The members-list {labelled-url-wiki-url} {url-wiki-session-cookie}[session cookie].
(If your group's members-list is stored at a {labelled-url-wiki-url} that requires {url-wiki-authentication}[authentication], this {url-wiki-session-cookie}[session cookie] should {url-wiki-authentication}[authenticate] TeX-Bot to view your group's members-list, as if it were {url-wiki-login-session}[logged in to the website] as a Committee member.
This can be {url-article-get-browser-cookies}[extracted from your web-browser], after logging in to view your members-list yourself.
It will probably be listed as a {url-wiki-cookie}[cookie] named {url-wiki-aspxauth-cookie}[`+.ASPXAUTH+`].)

You can put these {url-wiki-environment-variables}[variables] in a {url-wiki-env-files}[`+.env+` file] in the root folder, as {labelled-url-pythondotenv} is used to collect all {url-wiki-environment-variables}[environment variables].
There is an link:.env.example[`+.env.example+` file] in the repo that you can rename and populate.

There are also many other configuration settings that can be changed to alter the behaviour of TeX-Bot.
These are all listed in link:.env.example[the `+.env.example+` file], along with the behaviours that will be affected.

Any {url-wiki-environment-variables}[variables], in link:.env.example[the `+.env.example+` file], marked with `+# !!REQUIRED!!+` must be set before running TeX-Bot.
All other {url-wiki-environment-variables}[variables] are optional and their default values are shown as the example value for each variable in link:.env.example[the `+.env.example+` file].

[#local-deployment-running-tex-bot]
=== Running TeX-Bot

Once everything is set up, you should be able to execute the following command to automatically run TeX-Bot & connect it to your {url-discord-wiki-guild}[Discord guild]:

[source,console]
$ poetry run python -m main

[#contributing]
== Contributing

Contributions are welcome!

If you want to contribute, please {url-github-wiki-pull-request-creation}[create] a {url-github-wiki-pull-request}[pull request], and we'll review, test and (likely) merge it.
Please comment on any {url-project-bug-tracker}[issues] you'd like to work on, to prevent duplication of work.
If you find any bugs/problems or have any feature suggestions, please {url-github-wiki-issue-creation}[create] an {url-github-wiki-issue}[issue].

Before making contributions, it is highly suggested that you read xref:CONTRIBUTING.adoc[`+CONTRIBUTING.adoc+`].
This will ensure your code meets the standard required for this project and gives you the greatest chances of your contributions being merged.
