from typing import override

from .yamllocation import YAMLChunk

class YAML: ...

class Validator:
    def should_be_string(self, data: object, message: str) -> None: ...
    def to_yaml(self, data: object) -> object: ...

class MapValidator(Validator):
    _validator_dict: dict[str, Validator]

class ScalarValidator(Validator):
    def validate_scalar(self, chunk: YAMLChunk) -> object: ...

class Map(MapValidator):
    def __init__(
        self, validator_dict: dict[object, object], key_validator: Validator | None = ...
    ) -> None: ...

class Float(ScalarValidator):
    @override
    def validate_scalar(self, chunk: YAMLChunk) -> float: ...

class Int(ScalarValidator):
    @override
    def validate_scalar(self, chunk: YAMLChunk) -> int: ...

class Bool(ScalarValidator):
    @override
    def validate_scalar(self, chunk: YAMLChunk) -> bool: ...

class Str(ScalarValidator): ...

class Url(ScalarValidator):
    def __is_absolute_url(self, raw: str) -> bool: ...

class Regex(ScalarValidator):
    def __init__(self, regular_expression: str) -> None: ...

class SeqValidator(Validator): ...

class UniqueSeq(SeqValidator):
    def __init__(self, item_validator: Validator) -> None: ...

class Optional:
    def __init__(self, key: str, default: object = None, drop_if_none: bool = True) -> None: ...
