from collections.abc import Iterator
from typing import TypeVar, overload, override

from .yamllocation import YAMLChunk as YAMLChunk

_T = TypeVar("_T")

class YAML:
    def __init__(self, value: object) -> None: ...
    def __int__(self) -> int: ...
    def __unicode__(self) -> str: ...
    def revalidate(self, schema: 'Validator') -> None: ...
    @property
    def data(self) -> object: ...
    def as_marked_up(self) -> object: ...
    @property
    def start_line(self) -> int: ...
    @property
    def end_line(self) -> int: ...
    def lines(self) -> str: ...
    def lines_before(self, how_many: int) -> str: ...
    def lines_after(self, how_many: int) -> str: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, index: str | int | 'YAML') -> 'YAML': ...
    def __setitem__(self, index: str | int | 'YAML', value: object) -> None: ...
    def __delitem__(self, index: str | int | 'YAML') -> None: ...
    @override
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def as_yaml(self) -> str: ...
    def items(self) -> list[tuple[object, 'YAML']]: ...
    def keys(self) -> list[object]: ...
    def values(self) -> list['YAML']: ...
    def __iter__(self) -> Iterator['YAML']: ...
    def __contains__(self, item: str | int | 'YAML') -> bool: ...
    @property
    def validator(self) -> 'Validator | None': ...
    @property
    def text(self) -> str: ...
    def copy(self) -> 'YAML': ...
    def __gt__(self, val: object) -> bool: ...
    def __lt__(self, val: object) -> bool: ...
    @property
    def value(self) -> object: ...
    def is_mapping(self) -> bool: ...
    def is_sequence(self) -> bool: ...
    def is_scalar(self) -> bool: ...
    @property
    def scalar(self) -> object: ...
    def whole_document(self) -> object: ...
    @override
    def __eq__(self, value: object) -> bool: ...
    @override
    def __ne__(self, value: object) -> bool: ...

    @overload
    def get(self, index: str | int) -> 'YAML | None': ...
    @overload
    def get(self, index: str | int, default: _T) -> 'YAML | _T': ...

class Validator:
    def should_be_string(self, data: object, message: str) -> None: ...
    def to_yaml(self, data: object) -> object: ...

class ScalarValidator(Validator):
    def validate_scalar(self, chunk: YAMLChunk) -> object: ...

class SeqValidator(Validator): ...

class MapValidator(Validator):
    _validator_dict: dict[str | 'Optional', Validator]

class validators:
    MapValidator = MapValidator
    SeqValidator = SeqValidator
    ScalarValidator = ScalarValidator

class Map(MapValidator):
    def __init__(self, validator_dict: dict[object, object], key_validator: Validator | None = ...) -> None: ...

class MapPattern(MapValidator):
    def __init__(self, key_validator: Validator, value_validator: Validator) -> None: ...

class Str(ScalarValidator): 
    def validate_scalar(self, chunk: YAMLChunk) -> str: ...
class Int(ScalarValidator): 
    def validate_scalar(self, chunk: YAMLChunk) -> int: ...
class Float(ScalarValidator): 
    def validate_scalar(self, chunk: YAMLChunk) -> float: ...
class Bool(ScalarValidator): ...

class Regex(ScalarValidator):
    def __init__(self, regular_expression: str) -> None: ...

class CommaSeparated(SeqValidator):
    def __init__(self, item_validator: Validator) -> None: ...

class Enum(ScalarValidator):
    def __init__(self, expected: list[str] | frozenset[str] | set[str]) -> None: ...

class Optional:
    key: str
    def __init__(self, key: str, default: object = ...) -> None: ...

class Url(ScalarValidator): 
    def _Url__is_absolute_url(self, url: object) -> bool: ...

class UniqueSeq(SeqValidator):
    def __init__(self, item_validator: Validator) -> None: ...

def load(yaml_string: str, schema: Validator, label: str = ...) -> YAML: ...