from typing import TypeVar, overload

_T = TypeVar("_T")

class YAML:
    def __init__(self, value: object) -> None: ...
    @property
    def data(self) -> object: ...
    def as_yaml(self) -> str: ...
    def revalidate(self, schema: Validator) -> None: ...
    def __getitem__(self, item: str | int) -> YAML: ...
    def __setitem__(self, key: str | int, value: object) -> None: ...
    def __contains__(self, item: str) -> bool: ...
    def items(self) -> list[tuple[YAML, YAML]]: ...
    def keys(self) -> list[YAML]: ...
    def values(self) -> list[YAML]: ...

    @overload
    def get(self, index: str | int) -> YAML | None: ...

    @overload
    def get(self, index: str | int, default: _T) -> YAML | _T: ...


class Validator: ...

class Map(Validator):
    def __init__(self, validator_dict: dict[str | Optional, Validator]) -> None: ...

class MapPattern(Validator):
    def __init__(self, key_validator: Validator, value_validator: Validator) -> None: ...

class Str(Validator): ...
class Int(Validator): ...
class Float(Validator): ...
class Bool(Validator): ...

class Regex(Validator):
    def __init__(self, regular_expression: str) -> None: ...

class CommaSeparated(Validator):
    def __init__(self, item_validator: Validator) -> None: ...

class Enum(Validator):
    def __init__(self, expected: list[str]) -> None: ...

class Optional:
    def __init__(self, key: str, default: object = ...) -> None: ...

def load(yaml_string: str, schema: Validator, label: str = ...) -> YAML: ...
