import pathlib
from collections.abc import AsyncIterator

class AsyncPath(pathlib.PurePath):
    def __init__(self, *args: str | pathlib.Path | AsyncPath, **kwargs: object) -> None: ...
    async def stat(self, *, follow_symlinks: bool = ...) -> object: ...
    async def lstat(self) -> object: ...
    async def exists(self) -> bool: ...
    async def is_dir(self) -> bool: ...
    async def is_file(self) -> bool: ...
    async def is_mount(self) -> bool: ...
    async def is_symlink(self) -> bool: ...
    async def is_block_device(self) -> bool: ...
    async def is_char_device(self) -> bool: ...
    async def is_fifo(self) -> bool: ...
    async def is_socket(self) -> bool: ...
    async def samefile(self, other_path: str | pathlib.Path | AsyncPath) -> bool: ...

    # I/O operations
    async def open(
        self,
        mode: str = ...,
        buffering: int = ...,
        encoding: str | None = ...,
        errors: str | None = ...,
        newline: str | None = ...,
    ) -> object: ...
    async def read_bytes(self) -> bytes: ...
    async def read_text(self, encoding: str | None = ..., errors: str | None = ...) -> str: ...
    async def write_bytes(self, data: bytes) -> int: ...
    async def write_text(
        self, data: str, encoding: str | None = ..., errors: str | None = ...
    ) -> int: ...

    # File system modifications
    async def touch(self, mode: int = ..., exist_ok: bool = ...) -> None: ...
    async def mkdir(
        self, mode: int = ..., parents: bool = ..., exist_ok: bool = ...
    ) -> None: ...
    async def chmod(self, mode: int) -> None: ...
    async def lchmod(self, mode: int) -> None: ...
    async def unlink(self, missing_ok: bool = ...) -> None: ...
    async def rmdir(self) -> None: ...
    async def rename(self, target: str | pathlib.Path | AsyncPath) -> AsyncPath: ...
    async def replace(self, target: str | pathlib.Path | AsyncPath) -> AsyncPath: ...
    async def symlink_to(
        self, target: str | pathlib.Path | AsyncPath, target_is_directory: bool = ...
    ) -> None: ...
    async def hardlink_to(self, target: str | pathlib.Path | AsyncPath) -> None: ...
    async def link_to(self, target: str | pathlib.Path | AsyncPath) -> None: ...

    # Path resolution
    async def readlink(self) -> AsyncPath: ...
    async def resolve(self, strict: bool = ...) -> AsyncPath: ...
    async def absolute(self) -> AsyncPath: ...
    async def expanduser(self) -> AsyncPath: ...

    # Async Iterators
    def iterdir(self) -> AsyncIterator[AsyncPath]: ...
    def glob(self, pattern: str) -> AsyncIterator[AsyncPath]: ...
    def rglob(self, pattern: str) -> AsyncIterator[AsyncPath]: ...

class AsyncPosixPath(AsyncPath, pathlib.PurePosixPath): ...
class AsyncWindowsPath(AsyncPath, pathlib.PureWindowsPath): ...
