# Generated by Django 4.2.1 on 2023-05-12 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction_Reminder_Opt_Out_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_member_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f0-9]{64}\\Z', 'hashed_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Discord Member ID')),
            ],
            options={
                'verbose_name': 'Hashed Discord ID of Member that has Opted-Out of Interaction Reminders',
            },
        ),
        migrations.CreateModel(
            name='UoB_Made_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_uob_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f\\d]{64}\\Z', 'hashed_uob_id must be a valid sha256 hex-digest.')], verbose_name='Hashed UoB ID')),
            ],
            options={
                'verbose_name': 'Hashed UoB ID of User that has been made Member',
            },
        ),
    ]
