# Generated by Django 4.2.7 on 2023-12-04 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMemberStrikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_member_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f0-9]{64}\\Z', 'hashed_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Discord Member ID')),
                ('strikes', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of strikes')),
            ],
            options={
                'verbose_name': "Hashed Discord ID of a Discord Member that has been previously given one or more strikes because they broke one or more of your group's Discord guild rules",
                'verbose_name_plural': "Hashed Discord IDs of Discord Members that have been previously given one or more strikes because they broke one or more of your group's Discord guild rules",
            },
        ),
        migrations.CreateModel(
            name='DiscordReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_member_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f0-9]{64}\\Z', 'hashed_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Discord Member ID')),
                ('message', models.TextField(blank=True, max_length=1500, verbose_name='Message to remind User')),
                ('_channel_id', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('\\A\\d{17,20}\\Z', 'channel_id must be a valid Discord channel ID (see https://docs.pycord.dev/en/stable/api/abcs.html#discord.abc.Snowflake.id)')], verbose_name='Discord Channel ID of the channel that the reminder needs to be sent in')),
                ('_channel_type', models.IntegerField(blank=True, choices=[(0, 'text'), (1, 'private'), (2, 'voice'), (3, 'group'), (4, 'category'), (5, 'news'), (10, 'news_thread'), (11, 'public_thread'), (12, 'private_thread'), (13, 'stage_voice'), (14, 'directory'), (15, 'forum')], null=True, verbose_name='Discord Channel Type of the channel that the reminder needs to be sent in')),
                ('send_datetime', models.DateTimeField(verbose_name='Date & time to send reminder')),
            ],
            options={
                'verbose_name': 'A Reminder for a Discord Member',
                'verbose_name_plural': 'Reminders for Discord Members',
            },
        ),
        migrations.CreateModel(
            name='GroupMadeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_group_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f\\d]{64}\\Z', 'hashed_group_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Group ID')),
            ],
            options={
                'verbose_name': 'Hashed Group ID of User that has been made Member',
                'verbose_name_plural': 'Hashed Group IDs of Users that have been made Member',
            },
        ),
        migrations.CreateModel(
            name='IntroductionReminderOptOutMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_member_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f0-9]{64}\\Z', 'hashed_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Discord Member ID')),
            ],
            options={
                'verbose_name': 'Hashed Discord ID of a Discord Member that has Opted-Out of Introduction Reminders',
                'verbose_name_plural': 'Hashed Discord IDs of Discord Members that have Opted-Out of Introduction Reminders',
            },
        ),
        migrations.CreateModel(
            name='LeftDiscordMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_roles', models.JSONField(verbose_name='List of roles a Discord Member had')),
            ],
            options={
                'verbose_name': "A List of Roles that a Discord Member had when they left your group's Discord guild",
                'verbose_name_plural': "Lists of Roles that Discord Members had when they left your group's Discord guild",
            },
        ),
        migrations.CreateModel(
            name='SentGetRolesReminderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_member_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f0-9]{64}\\Z', 'hashed_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Discord Member ID')),
            ],
            options={
                'verbose_name': 'Hashed Discord ID of a Discord Member that has had a "Get Roles" reminder sent to their DMs',
                'verbose_name_plural': 'Hashed Discord IDs of Discord Members that have had a "Get Roles" reminder sent to their DMs',
            },
        ),
        migrations.CreateModel(
            name='SentOneOffIntroductionReminderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_member_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f0-9]{64}\\Z', 'hashed_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Discord Member ID')),
            ],
            options={
                'verbose_name': 'Hashed Discord ID of a Discord Member that has had a one-off Introduction reminder sent to their DMs',
                'verbose_name_plural': 'Hashed Discord IDs of Discord Members that have had a one-off Introduction reminder sent to their DMs',
            },
        ),
        migrations.AddConstraint(
            model_name='discordreminder',
            constraint=models.UniqueConstraint(fields=('hashed_member_id', 'message', '_channel_id'), name='unique_user_channel_message'),
        ),
    ]
