# Generated by Django 4.2.8 on 2024-01-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmademember',
            old_name='hashed_group_id',
            new_name='hashed_group_member_id',
        ),
    ]
