# Generated by Django 4.2.8 on 2024-01-01 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_hashed_group_id_groupmademember_hashed_group_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmademember',
            name='hashed_group_member_id',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f\\d]{64}\\Z', 'hashed_group_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Group Member ID'),
        ),
    ]
