# Generated by Django 4.2.1 on 2023-06-20 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discordreminder_leftmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentOneOffInteractionReminderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_member_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f0-9]{64}\\Z', 'hashed_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Discord Member ID')),
            ],
            options={
                'verbose_name': 'Hashed Discord ID of Member that has had a one-off interaction reminder sent to their DMs',
            },
        ),
        migrations.AlterModelOptions(
            name='sentgetrolesremindermember',
            options={'verbose_name': 'Hashed Discord ID of Member that has had a "Get Roles" reminder sent to their DMs'},
        ),
    ]
