# Generated by Django 4.2.9 on 2024-01-12 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_memberstrikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberStrikes',
            new_name='DiscordMemberStrikes',
        ),
        migrations.AlterModelOptions(
            name='discordmemberstrikes',
            options={'verbose_name': "Hashed Discord ID of a Discord Member that has been previously given one or more strikes because they broke one or more of your group's Discord guild rules", 'verbose_name_plural': "Hashed Discord IDs of Discord Members that have been previously given one or more strikes because they broke one or more of your group's Discord guild rules"},
        ),
        migrations.AlterModelOptions(
            name='introductionreminderoptoutmember',
            options={'verbose_name': 'Hashed Discord ID of a Discord Member that has Opted-Out of Introduction Reminders', 'verbose_name_plural': 'Hashed Discord IDs of Discord Members that have Opted-Out of Introduction Reminders'},
        ),
        migrations.AlterModelOptions(
            name='leftmember',
            options={'verbose_name': "A List of Roles that a Discord Member had when they left your group's Discord guild", 'verbose_name_plural': "Lists of Roles that Discord Members had when they left your group's Discord guild"},
        ),
        migrations.AlterModelOptions(
            name='sentgetrolesremindermember',
            options={'verbose_name': 'Hashed Discord ID of a Discord Member that has had a "Get Roles" reminder sent to their DMs', 'verbose_name_plural': 'Hashed Discord IDs of Discord Members that have had a "Get Roles" reminder sent to their DMs'},
        ),
        migrations.AlterModelOptions(
            name='sentoneoffintroductionremindermember',
            options={'verbose_name': 'Hashed Discord ID of a Discord Member that has had a one-off Introduction reminder sent to their DMs', 'verbose_name_plural': 'Hashed Discord IDs of Discord Members that have had a one-off Introduction reminder sent to their DMs'},
        ),
        migrations.AlterModelOptions(
            name='uobmademember',
            options={'verbose_name': 'Hashed Group ID of User that has been made Member', 'verbose_name_plural': 'Hashed Group IDs of Users that have been made Member'},
        ),
        migrations.AlterField(
            model_name='leftmember',
            name='_roles',
            field=models.JSONField(verbose_name='List of roles a Discord Member had'),
        ),
        migrations.AlterField(
            model_name='uobmademember',
            name='hashed_uob_id',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f\\d]{64}\\Z', 'hashed_group_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Group Member ID'),
        ),
    ]
