# Generated by Django 5.0.6 on 2024-05-15 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_hashed_uob_id_groupmademember_hashed_group_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_member_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[A-Fa-f0-9]{64}\\Z', 'hashed_member_id must be a valid sha256 hex-digest.')], verbose_name='Hashed Discord Member ID')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Description of the action')),
            ],
            options={
                'verbose_name': 'An Action for a Discord Member',
                'verbose_name_plural': 'Actions for Discord Members',
            },
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('hashed_member_id', 'description'), name='unique_user_action'),
        ),
    ]
