# Generated by Django 5.0.4 on 2024-05-18 23:20

import django.db.models.deletion
from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240519_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordmemberstrikes',
            name='hashed_member_id',
        ),
        migrations.RemoveField(
            model_name='discordmemberstrikes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='discordreminder',
            name='hashed_member_id',
        ),
        migrations.RemoveField(
            model_name='introductionreminderoptoutmember',
            name='hashed_member_id',
        ),
        migrations.RemoveField(
            model_name='introductionreminderoptoutmember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sentgetrolesremindermember',
            name='hashed_member_id',
        ),
        migrations.RemoveField(
            model_name='sentgetrolesremindermember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sentoneoffintroductionremindermember',
            name='hashed_member_id',
        ),
        migrations.RemoveField(
            model_name='sentoneoffintroductionremindermember',
            name='id',
        ),
        migrations.AlterField(
            model_name='discordmemberstrikes',
            name='discord_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='strikes', serialize=False, to='core.discordmember', verbose_name='Discord Member')
        ),
        migrations.AlterField(
            model_name='discordreminder',
            name='discord_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.discordmember', verbose_name='Discord Member')
        ),
        migrations.AlterField(
            model_name='introductionreminderoptoutmember',
            name='discord_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='opted_out_of_introduction_reminders', serialize=False, to='core.discordmember', verbose_name='Discord Member')
        ),
        migrations.AlterField(
            model_name='sentgetrolesremindermember',
            name='discord_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sent_get_roles_reminder', serialize=False, to='core.discordmember', verbose_name='Discord Member')
        ),
        migrations.AlterField(
            model_name='sentoneoffintroductionremindermember',
            name='discord_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sent_one_off_introduction_reminder', serialize=False, to='core.discordmember', verbose_name='Discord Member')
        ),
        migrations.AddConstraint(
            model_name='discordreminder',
            constraint=models.UniqueConstraint(fields=('discord_member', 'message', '_channel_id'), name='unique_user_channel_message'),
        ),
    ]
