# Generated by Django 5.0.7 on 2024-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20240519_0020"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocietyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guild_event_id",
                    models.IntegerField(unique=True, verbose_name="Guild Event ID"),
                ),
                (
                    "gcal_event_id",
                    models.TextField(
                        unique=True, verbose_name="Google Calendar Event ID"
                    ),
                ),
                (
                    "discord_event_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="Discord Event ID"
                    ),
                ),
                ("event_name", models.TextField(verbose_name="Event Name")),
                (
                    "event_description",
                    models.TextField(verbose_name="Event Description"),
                ),
                (
                    "event_start_time",
                    models.DateTimeField(verbose_name="Event Start Time"),
                ),
                ("event_end_time", models.DateTimeField(verbose_name="Event End Time")),
                ("event_location", models.TextField(verbose_name="Event Location")),
            ],
            options={
                "verbose_name": "Society Event",
            },
        ),
        migrations.AddConstraint(
            model_name="societyevent",
            constraint=models.UniqueConstraint(
                fields=("guild_event_id", "gcal_event_id", "discord_event_id"),
                name="unique_society_event",
            ),
        ),
    ]
