# Generated by Django 5.1.3 on 2024-11-07 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240519_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCommitteeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('status', models.CharField(choices=[('BLK', 'Blocked'), ('CND', 'Cancelled'), ('CMP', 'Complete'), ('INP', 'In Progress'), ('NST', 'Not Started')], default='NST', max_length=3)),
                ('discord_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_committee_actions', to='core.discordmember', verbose_name='Discord Member')),
            ],
            options={
                'verbose_name': 'Assigned Committee Action',
                'constraints': [models.UniqueConstraint(fields=('discord_member', 'description'), name='unique_user_action')],
            },
        ),
    ]
