# Generated by Django 5.2.5 on 2025-09-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_discordmember_alter_discordmemberstrikes_options_and_more_squashed_0011_alter_assignedcommitteeaction_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcommitteeaction',
            old_name='status',
            new_name='raw_status',
        ),
    ]
