name: Github Container Registry Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: docker/setup-buildx-action@v2
    -
      uses: docker/build-push-action@v4
      with:
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
