name: Github Container Registry Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: docker/setup-buildx-action@v2
    -
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    -
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/cssuob/tex-bot-py:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
