name: Auto-update pull request branches

"on":
    push: ~

concurrency:  # yamllint disable-line rule:key-ordering
    cancel-in-progress: true
    group: ${{github.workflow}}-${{github.ref}}

permissions:
    contents: none  # Default permissions reset to none

jobs:
    pr-auto-update:
        name: Auto-update pull request branches
        runs-on: ubuntu-latest

        steps:
            - id: generate-token
              name: Generate access token
              uses: actions/create-github-app-token@v3
              with:
                client-id: ${{vars.PR_AUTO_UPDATE_CLIENT_ID}}
                permission-contents: write
                permission-pull-requests: write
                private-key: ${{secrets.PR_AUTO_UPDATE_PRIVATE_KEY}}  # zizmor: ignore[secrets-outside-env]

            - uses: CSSUoB/pr-auto-updater@v3.0.0
              env:  # yamllint disable-line rule:key-ordering
                GITHUB_TOKEN: ${{steps.generate-token.outputs.token}}
                MERGE_CONFLICT_ACTION: label
                MERGE_CONFLICT_LABEL: conflict
                PR_FILTER: labelled
                PR_LABELS: sync
