name: Build Dev Container Image & Push To GitHub Container Registry

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/cssuob/tex-bot-py-v2:dev-${{ github.ref }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
