name: Build Container Image & Push To Github Container Registry

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: docker/setup-buildx-action@v2
    -
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    -
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/cssuob/texbot-py-v2:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
